baseURL: "https://jeans-github.github.io/"
languageCode: en-us
title: Jean SEVAUX

theme: "PaperMod"

paginate: 5

enableRobotsTXT: true
enableEmoji: true

googleAnalytics: "G-C3YDT1E2YB"

taxonomies:
  category: categories
  series: series
  tag: tags

menu:
  main:
    - name: Posts
      url: /posts
      weight: 1
      
    - name: About
      url: /about
      weight: 2

    - name: Contact
      url: /contact
      weight: 3

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  # env: production
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true    # Adds a Previous / Next post suggestion under a single post
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true   # Table of Content
  ShowBreadCrumbs: true # fil d'Ariane

assets:
    favicon: "favicon.ico"  # default path is /static

# **************************************************
  profileMode:
    enabled: true
    #title: "\\> Hello there <"
    title: "\\> Bienvenue \U0001F44B <"
    subtitle: "*Check my Github repositories and add \U00002B50!*"
    imageUrl: "/images/gorilla-reduce.jpg"
    imageTitle: "General Kenobi"
    #imageWidth: 120 # custom size
    #imageHeight: 120 # custom size
    buttons:
      - name: About Me
        url: "/about"
      - name: Posts
        url: "/posts"

# **************************************************
  homeInfoParams:
    enabled: false
    Title: "\\> Hi there \U0001F44B"
    Content: >
      Welcome to my personal website!

        - Do give a ðŸŒŸ on my Github repos!
        - check about page, to know more about me

# **************************************************
  socialIcons:
    - name: "LinkedIn"
      url: "https://linkedin.com/in/jean-sevaux"
    - name: "Github"
      url: "https://github.com/JeanS-github"
    - name: Rss
      url: "index.xml"

